---
- name: Pull Spring image of Review App
  hosts: all
  tasks:
    - name: Pull app image
      docker_image:
        name: himanshu6398/startup_review-spring
        source: pull
    - name: Running the container
      docker_container:
        name: startupreview-spring
        image: himanshu6398/startup_review-spring:latest
        state: started
        restart: yes
        ports:
          - "8081:8081"
        networks:
          - name: app-default
#         restart_policy: always
